### PR TITLE
Expand admin interface

### PR DESCRIPTION
**Pull request by shimonp21**

### CODE REVIEW

**Comment by shimonp21** [comment]
@qmerotto Hello! Would be happy if you could take a look at my PR - it should make the `admins` interface more useful.

**Review by qmerotto — APPROVED** [review]
lgtm

**Comment by shimonp21** [comment]
@qmerotto Please merge+release if possible? :)

**Comment by shimonp21** [comment]
@qmerotto Gentle ping :)

**Comment by mahaben** [comment]
@shimonp21 Done :)

**Pull request merged**
